# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Email_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Phone_Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Street_Adresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Street_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('country', 'state', 'city'),
            },
        ),
        migrations.AddField(
            model_name='person_street_adresses',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Persons'),
        ),
        migrations.AddField(
            model_name='person_street_adresses',
            name='street_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Street_Addresses'),
        ),
        migrations.AddField(
            model_name='person_phone_numbers',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Persons'),
        ),
        migrations.AddField(
            model_name='person_email_addresses',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Persons'),
        ),
        migrations.AddField(
            model_name='members',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_book.Persons'),
        ),
    ]
