# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='person_email_addresses',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='person_phone_numbers',
            unique_together=set([('country_code', 'phone_no')]),
        ),
        migrations.AlterUniqueTogether(
            name='street_addresses',
            unique_together=set([('country', 'state', 'city')]),
        ),
    ]
