# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20160918_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Street_Adresses',
            new_name='Person_Street_Addresses',
        ),
    ]
